import * as githubSecrets from './github/secrets';
import './google/api-services';
import './google/artifacts-bucket-iam';
import './google/big-query';
import './google/deploy-service-account';
import './google/iam';
import './google/project';
import './google/reseller-service-account';
import './google/slack-logger';
import './services/workspace-agent/reseller-subscription';
import './services/workspace-agent/service-account';
import './services/workspace-agent/workspace-agent';
import './services/workspace-agent/workspace-agent-v2';
import './services/consumer-api/service-account';
import './services/consumer-api/consumer-api';
import './services/tripletex-agent/service-account';
import './services/tripletex-agent/tripletex-agent';
import './services/freshworks-agent/service-account';
import './services/freshworks-agent/freshworks-agent';
import './services/freshworks-agent/schedule';

export { githubSecrets };
