name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    # TODO: Set project URL
    # env:
    # PROJECT_URL: https://github.com/orgs/ORG/projects/PROJECT_ID
    steps:
      - if: env.PROJECT_URL != ''
        uses: actions/add-to-project@v0.4.1
        with:
          project-url: ${{ env.PROJECT_URL }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["needs-refinement", "needs-triage"]
            })
