name: Drift check
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-for-changes:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_PROJECT_SA_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          export_default_credentials: true
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - run: yarn install
      - uses: pulumi/actions@v3
        with:
          command: preview
          refresh: true
          cloud-url: gs://ayr-pulumi/infra-core
          stack-name: prod
          expect-no-changes: true
