name: Pull Request
on:
  pull_request:

jobs:
  preview-changes:
    name: Preview changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_PROJECT_SA_KEY }}

      - run: yarn install

      - uses: pulumi/actions@v4
        with:
          command: preview
          refresh: true
          cloud-url: gs://ayr-pulumi/infra-core
          stack-name: prod
          comment-on-pr: true
          github-token: ${{ secrets.AYRBOT_GITHUB_TOKEN }}
