name: Push
on:
  push:
    branches:
      - main

jobs:
  apply-changes:
    name: Apply changes
    runs-on: ubuntu-latest
    concurrency: pulumi-up
    steps:
      - uses: actions/checkout@v3

      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_PROJECT_SA_KEY }}

      - run: yarn install

      - uses: pulumi/actions@v3
        with:
          command: up
          # refresh: true
          cloud-url: gs://ayr-pulumi/infra-core
          stack-name: prod
