name: Update tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Which tag
        required: true
      service:
        description: Which service
        required: true
  repository_dispatch:
    types: [update_tag]
jobs:
  update-tag:
    name: Update tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cobraz/setup-variables@v1
        id: vars
        with:
          key: ${{ github.event_name }}
          map: |
            repository_dispatch: '{"tag": "${{ github.event.client_payload.tag }}", "service": "${{ github.event.client_payload.service }}"}'
            workflow_dispatch: '{"tag": "${{ github.event.inputs.tag }}", "service": "${{ github.event.inputs.service }}"}'

      - run: echo ${{ steps.vars.outputs.result }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_PROJECT_SA_KEY }}

      - uses: cobraz/pulumi-set-config@main
        id: config
        env:
          GITHUB_TOKEN: ${{ secrets.INDIVBOT_GITHUB_TOKEN }}
        with:
          stack-name: prod
          cloud-url: gs://ayr-pulumi/infra-core
          key: ${{ fromJson(steps.vars.outputs.result).service }}:tag
          value: ${{ fromJson(steps.vars.outputs.result).tag }}

      - name: Get commits
        uses: actions/github-script@v6
        id: changelog
        with:
          github-token: ${{ secrets.AYRBOT_GITHUB_TOKEN }}
          result-encoding: string
          script: |

            const [,head] = '${{ fromJson(steps.vars.outputs.result).tag }}'.split('-');
            const [,base] = '${{ fromJson(steps.config.outputs.key).value }}'.split('-');

            const compare = await github.repos.compareCommits({
              owner: 'ayrorg',
              repo: '${{ fromJson(steps.vars.outputs.result).service }}',
              base,
              head,
            });

            const parseCommit = (message) => message.split('\n')[0].replace('#', 'ayrorg/${{ fromJson(steps.vars.outputs.result).service }}#');
            const changelog = compare.data.commits.map(commit => `* ${parseCommit(commit.commit.message)} ([commit](${commit.html_url}))`).join('\n');

            console.log(changelog);
            return changelog;

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.AYRBOT_GITHUB_TOKEN }}
          commit-message:
            bump ${{ fromJson(steps.vars.outputs.result).service }} to ${{
            fromJson(steps.vars.outputs.result).tag }}
          title:
            'chore: bump ${{ fromJson(steps.vars.outputs.result).service }} tag
            to `${{ fromJson(steps.vars.outputs.result).tag }}`'
          body: |
            Automated tag change. 🎉

            ${{ steps.changelog.outputs.result }}
          branch: bump-tag-${{ fromJson(steps.vars.outputs.result).service }}
          team-reviewers: developers
